controller_list:
  - name: fake_claw_controller
    joints:
      - right_knuckle_joint
  - name: fake_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_flex_joint
      - wrist_roll_joint